postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: adminadmin
    POSTGRES_DB: imixs-microservice

imixsmicroservice:
  image: imixs/imixs-microservice
  environment:
    WILDFLY_PASS: adminadmin
  ports:
    - "8080:8080"
    - "9990:9990"
  links: 
    - postgres:postgres
 

    
 